path.data: data
path.logs: log


api:
  enabled: true
  network:
    binding: 0.0.0.0:9200
  tls:
    enabled: false

elasticsearch:
- name: default
  enabled: true
  endpoint: http://30.11.215.238:9200
#  index_prefix: proxy-
  basic_auth:
    username: elastic
    password: fe204exd9oCdU7YpO5F2V806


cache:
  enabled: false
  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0
  #Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  ttl: 60s

plugins:
- name: proxy
  enabled: true
  pass_through: []
  upstream:
  - name: primary
    enabled: true
    cache:
      enabled: true
    rate_limit:
      max_qps: 10000
    queue_name: primary
    max_queue_depth: -1
    timeout: 60s
    elasticsearch: default

- name: floating_ip
  enabled: false
  ip: 192.168.1.222
  netmask: 255.255.255.0
  interface: en0
  priority: 100

pipelines:
- name: primary
  start:
    joint: index
    enabled: true
  process: []
  error:
    joint: logging
    enabled: true


modules:
- name: elastic
  elasticsearch: default
  enabled: true
  indexer_enabled: true
  store_enabled: true
  orm_enabled: true

- name: pipeline
  enabled: true
  runners:
    - name: primary
      enabled: true
      input_queue: primary
      max_go_routine: 3
      threshold_in_ms: 0
      timeout_in_ms: 5000
      pipeline_id: primary
