version: "3.5"

services:
  infini-elasticsearch-proxy:
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - 2900:2900
    container_name: "infini-elasticsearch-proxy"
    volumes:
      - ../:/go/src/infini-gateway

volumes:
  dist: